### ISSUE TITLE
 Release界面的发行版可以不用全打包的

### ISSUE THREAD

**Issue by Anz-03** [Nostalgia-WZQ/MyTools#1]
我自己克隆了你的代码，重新用visual studio打包发现可以只要10m就行了
![image](https://github.com/Nostalgia-WZQ/MyTools/assets/106299500/44c657f2-8a69-496e-ad05-ac05ea822b52)

**Comment by Nostalgia-WZQ** [comment]
> 我自己克隆了你的代码，重新用visual studio打包发现可以只要10m就行了
> ![image](https://github.com/Nostalgia-WZQ/MyTools/assets/106299500/44c657f2-8a69-496e-ad05-ac05ea822b52)
> 

是的，properties/publishprofiles/*.pubxml文件里可以设置SelfContained属性，默认是false（依赖于框架）（这个文件没有上传到github，你克隆后打包发布时应该会提示没有这个文件，所以自动用了默认值false）。
我是用vs2022项目模板创建的，它里面设置的是true（独立），所以打包时把框架也打包了，后续打包发布会改为false。
