### ISSUE TITLE
建议加入合并音视频

### ISSUE THREAD

**Issue by Anz-03** [Nostalgia-WZQ/MyTools#2]
其实我已经将这些功能以命令行的形式在我电脑上实现的
是用Python调用ffmpeg实现的，现在我将源代码给你（不直接使用windows 批处理的原因是因为他的语法太奇怪了，学了记记了又忘，平常还用的少）
这是合并音视频的
import os

input_audio_filename_list = os.listdir("./Input_audio")
input_video_filename_list = os.listdir("./Input_video")

for i in range(len(input_audio_filename_list)):
    a=input_audio_filename_list[i]
    b=input_video_filename_list[i]
    if(b[:-4]==".mp4"):
        os.system(f"ffmpeg -i \"./Input_audio/{a}\" -i \"./Input_video/{b}\" -c:v copy -c:a copy -strict experimental \"./Output/{b}\"")
    else:
        b_splt=b.split('.')
        b_re=''.join([b_splt[i] for i in range(len(b_splt)-1)])
        os.system(f"ffmpeg -i \"./Input_audio/{a}\" -i \"./Input_video/{b}\" -c:v copy -c:a copy -strict experimental \"./Output/{b_re}.mp4\"")
    # os.system(f"ffmpeg -i \"./Input_audio/{a}\" -i \"./Input_video/{b}\" -c:v copy -c:a copy -strict experimental \"./Output/{a[:-4]}.mkv\"")

在这个中间做了一些字符串的转换，是因为有各种各样奇怪的格式，有的格式后缀名只有两个字符，有的有三个字符，有的有4个字符

**Comment by Nostalgia-WZQ** [comment]
好的，我等看一下

**Comment by Nostalgia-WZQ** [comment]
你的-c:v copy -c:a copy -strict experimental这条命令我试了一下，对于视频时长长于音频时长的情况会不生效，合成后仍然用的原音频，感觉用-map 0:v:0 -map 1:a:0 -c copy这条命令更通用一些。还有你是需要转换后都是mp4格式吗？我目前代码逻辑是利用原视频扩展名（当然也可以在代码中指定特定扩展名，但这样就被限制了），之后我会在”设置“页面增加自定义项，包括命令、后缀、扩展名等（计划）。
